name: main

on:
  push:
    branches: [ main ]

env:
  SEMVERBOT_VERSION: "v1.7.2"

jobs:
  build:
    name: semverbot release
    runs-on: [self-hosted, linux, deb12]
    steps:
      - uses: actions/checkout@v2

      - name: set up git
        run: |
          sudo apt install -y git
          
      - name: set up path
        run: |
          mkdir bin
          echo "$(pwd)/bin" >> $GITHUB_PATH
          echo $PWD
          ls -ltR
          git status -v

      - name: install semverbot
        run: |
          curl -o bin/sbot -L https://github.com/restechnica/semverbot/releases/download/$SEMVERBOT_VERSION/sbot-linux-amd64
          chmod +x bin/sbot
          
      - name: update version
        run: |
          sbot update version
          current_version="$(sbot get version)"
          release_version="$(sbot predict version)"
          
          echo "CURRENT_VERSION=${current_version}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${release_version}" >> $GITHUB_ENV
          
          echo "current version: ${current_version}"
          echo "next version: ${release_version}"
          
      - name: release version
        run: |
          sbot release version
          sbot push version
